name: example-subfolders
on: [push, pull_request]
jobs:
  separate-actions:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macOS-latest]
    name: Test on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      # for internal testing, let's use the local action
      - uses: ./
        with:
          # server use NPM package lock file
          working-directory: examples/subfolders/server
      - uses: ./
        with:
          # client uses yarn lock
          working-directory: examples/subfolders/client
      # run tests
      - run: npm t
        working-directory: examples/subfolders/server
      - run: npm t
        working-directory: examples/subfolders/client

  separate-lines:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macOS-latest]
    name: Test on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          # specify a directory per line
          working-directory: |
            examples/subfolders/server
            examples/subfolders/client
      # run tests
      - run: npm t
        working-directory: examples/subfolders/server
      - run: npm t
        working-directory: examples/subfolders/client
