name: example-node-version
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      # pick the Node version to use and install it
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - uses: ./
        with:
          working-directory: examples/basic
      - run: |
          node --version
          npm --version
