name: example-basic
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          working-directory: examples/basic
      - run: npm t
        working-directory: examples/basic
